name: the_country_number
description: A small library for flutter written in pure dart (doesn't use libphonenumber) which parses a phone number or iso2 code of a country to give you some vitals about the country (if you need to skip null-safety, use version 0.9.0)
version: 0.9.2+6
homepage: https://github.com/ondbyte/the_country_number

environment:
  sdk: ">=2.12.0-0 <3.0.0"

#dependencies:

dev_dependencies:
  test:

